name: uuvpn
description: ios/android vpn proxy client application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+280

environment:
  sdk: ">=3.0.1 <4.0.0"  # 更新为与 Flutter 3.10.1 兼容的 SDK 版本

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  another_flushbar: ^1.12.30
  cupertino_icons: ^1.0.5
  dio: ^5.5.0+1
  fluro: ^2.0.3
  shared_preferences: ^2.0.15
  webview_flutter: ^3.0.4
  provider: ^6.0.3
  flutter_svg: ^0.23.0+1 
  flutter_screenutil: ^5.9.3 
  flutter_swiper_plus: ^2.0.4 
  flutter_login: ^5.0.0
  flutter_easyrefresh: ^2.1.8
  intl: ^0.18.1
  path_provider: ^2.0.10 
  crisp: ^0.3.1
  modal_bottom_sheet: ^3.0.0-pre 
  fluttertoast: ^8.0.9
  meta: ^1.7.0
  flutter_icmp_ping: ^3.1.0
  url_launcher: ^6.1.11
  synchronized: ^3.1.0
  convert: ^3.1.1
  crypto: ^3.0.3
  get: ^4.6.5
  google_fonts: ^5.0.0
  sync_http: ^0.3.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/flags/
    - assets/
  fonts:
    - family: Aquire
      fonts:
        - asset: assets/font/Aquire.otf
