name: Build and Publish Android

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.3'

    - name: Build with Flutter
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: android-app
        path: build/app/outputs/flutter-apk/app-release.apk
